@echo off
echo [Cassandra] insert 10k...
python main.py --system cassandra --operation insert --dataset data\dataset_10000.json --size 10000 --scenario insert_10k
echo [Cassandra] read 10k...
python main.py --system cassandra --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k
echo [Cassandra] update 10k...
python main.py --system cassandra --operation update --dataset data\dataset_10000.json --size 10000 --scenario update_10k
echo [Cassandra] delete 10k...
python main.py --system cassandra --operation delete --dataset data\dataset_10000.json --size 10000 --scenario delete_10k
echo [Cassandra] query 10k...
python main.py --system cassandra --operation query --dataset data\dataset_10000.json --size 10000 --scenario query_10k
echo [Cassandra] insert 100k...
python main.py --system cassandra --operation insert --dataset data\dataset_100000.json --size 100000 --scenario insert_100k
echo [Cassandra] read 100k...
python main.py --system cassandra --operation read --dataset data\dataset_100000.json --size 100000 --scenario read_100k
echo [Cassandra] read 10k concurrency=10...
python main.py --system cassandra --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k_c10 --concurrency 10
echo [Cassandra] Done!
