@echo off
echo ============================================================
echo  PolyStoreBench -- MongoDB + Redis + Spark Benchmarks
echo ============================================================

echo [MongoDB] insert 10k...
python main.py --system mongodb --operation insert --dataset data\dataset_10000.json --size 10000 --scenario insert_10k
echo [MongoDB] read 10k...
python main.py --system mongodb --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k
echo [MongoDB] update 10k...
python main.py --system mongodb --operation update --dataset data\dataset_10000.json --size 10000 --scenario update_10k
echo [MongoDB] delete 10k...
python main.py --system mongodb --operation delete --dataset data\dataset_10000.json --size 10000 --scenario delete_10k
echo [MongoDB] query 10k...
python main.py --system mongodb --operation query --dataset data\dataset_10000.json --size 10000 --scenario query_10k
echo [MongoDB] insert 100k...
python main.py --system mongodb --operation insert --dataset data\dataset_100000.json --size 100000 --scenario insert_100k
echo [MongoDB] read 100k...
python main.py --system mongodb --operation read --dataset data\dataset_100000.json --size 100000 --scenario read_100k
echo [MongoDB] query 100k...
python main.py --system mongodb --operation query --dataset data\dataset_100000.json --size 100000 --scenario query_100k
echo [MongoDB] read 10k concurrency=10...
python main.py --system mongodb --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k_c10 --concurrency 10

echo [Redis] insert 10k...
python main.py --system redis --operation insert --dataset data\dataset_10000.json --size 10000 --scenario insert_10k
echo [Redis] read 10k...
python main.py --system redis --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k
echo [Redis] update 10k...
python main.py --system redis --operation update --dataset data\dataset_10000.json --size 10000 --scenario update_10k
echo [Redis] delete 10k...
python main.py --system redis --operation delete --dataset data\dataset_10000.json --size 10000 --scenario delete_10k
echo [Redis] insert 100k...
python main.py --system redis --operation insert --dataset data\dataset_100000.json --size 100000 --scenario insert_100k
echo [Redis] read 100k...
python main.py --system redis --operation read --dataset data\dataset_100000.json --size 100000 --scenario read_100k
echo [Redis] read 10k concurrency=10...
python main.py --system redis --operation read --dataset data\dataset_10000.json --size 10000 --scenario read_10k_c10 --concurrency 10

echo [Spark] insert 10k...
python main.py --system spark --operation insert --dataset data\dataset_10000.csv --size 10000 --scenario insert_10k
echo [Spark] read 10k...
python main.py --system spark --operation read --dataset data\dataset_10000.csv --size 10000 --scenario read_10k
echo [Spark] update 10k...
python main.py --system spark --operation update --dataset data\dataset_10000.csv --size 10000 --scenario update_10k
echo [Spark] query 10k...
python main.py --system spark --operation query --dataset data\dataset_10000.csv --size 10000 --scenario query_10k
echo [Spark] delete 10k...
python main.py --system spark --operation delete --dataset data\dataset_10000.csv --size 10000 --scenario delete_10k
echo [Spark] insert 100k...
python main.py --system spark --operation insert --dataset data\dataset_100000.csv --size 100000 --scenario insert_100k
echo [Spark] read 100k...
python main.py --system spark --operation read --dataset data\dataset_100000.csv --size 100000 --scenario read_100k
echo [Spark] update 100k...
python main.py --system spark --operation update --dataset data\dataset_100000.csv --size 100000 --scenario update_100k
echo [Spark] query 100k...
python main.py --system spark --operation query --dataset data\dataset_100000.csv --size 100000 --scenario query_100k
echo [Spark] delete 100k...
python main.py --system spark --operation delete --dataset data\dataset_100000.csv --size 100000 --scenario delete_100k

echo ============================================================
echo  Done! Cassandra benchmarks require container to be healthy.
echo  Run scripts\run_cassandra.bat after: docker ps shows (healthy)
echo ============================================================
